# Task 1

Dataset from Kaggle: FIFA  Complete Player Dataset (From Big 5 Leagues)

Contains player attributes like overall rating, value, wage, position, nationality, club, and 70+ skill stats.

Goal: Analyze player performance, market value, and league/club trends across Europe's top 5 leagues.

   # Questions
  
1. What is the average Exam_Score per Motivation_Level?
2. Which Gender has a higher average Exam_Score?
3. Do students with Internet_Access score higher on average?
4. What is the average Hours_Studied for each Family_Income level?
5. How many students have Learning_Disabilities and what is their avg score?
6. What is the average Exam_Score per School_Type (Public vs Private)?
7. Who are the top 10 highest scoring students and how many hours did they study?
8. Is there a correlation between Hours_Studied, Attendance, Sleep_Hours and Exam_Score?
9. What is the average Exam_Score per Parental_Education_Level?
10. How many students attend tutoring sessions and does it affect their score?
11. What is the average Attendance per Peer_Influence type?
12. What is the average Exam_Score for each combination of School_Type and Family_Income? (pivot table)
13. How many students have Attendance below 70 and what is their avg Exam_Score?
14. What is the max and min Exam_Score per Distance_from_Home?
15. Is there a correlation between Parental_Involvement and Exam_Score?

# 1- Understanding data

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv('StudentPerformanceFactors.csv', low_memory=False)
df.describe()

,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,7647.000000,7647.000000,7647.000000,7647.000000,7647.000000,7647.000000
mean,79.977769,7.017654,75.115470,1.488296,2.969400,67.319733
std,11.580492,1.467880,14.418455,1.223768,1.027788,7.843480
min,60.000000,4.000000,50.000000,0.000000,0.000000,-20.000000
25%,70.000000,6.000000,63.000000,1.000000,2.000000,65.000000
50%,80.000000,7.000000,75.000000,1.000000,3.000000,67.000000
75%,90.000000,8.000000,88.000000,2.000000,4.000000,69.000000
max,100.000000,10.000000,100.000000,8.000000,6.000000,150.000000

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7647 entries, 0 to 7646
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               7629 non-null   str
 1   Attendance                  7647 non-null   int64
 2   Parental_Involvement        7647 non-null   str
 3   Access_to_Resources         7647 non-null   str
 4   Extracurricular_Activities  7647 non-null   str
 5   Sleep_Hours                 7647 non-null   int64
 6   Previous_Scores             7647 non-null   int64
 7   Motivation_Level            7647 non-null   str
 8   Internet_Access             7647 non-null   str
 9   Tutoring_Sessions           7647 non-null   int64
 10  Family_Income               7647 non-null   str
 11  Teacher_Quality             7558 non-null   str
 12  School_Type                 7647 non-null   str
 13  Peer_Influence              7647 non-null   str
 14  Physical_Activity           7647 non-null   int64
 15  Learning_Disabilities       7647 non-null   str
 16  Parental_Education_Level    7538 non-null   str
 17  Distance_from_Home          7565 non-null   str
 18  Gender                      7647 non-null   str
 19  Exam_Score                  7647 non-null   int64
dtypes: int64(6), str(14)
memory usage: 1.2 MB

In [3]:
df.head(10)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,LOW,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,150
1,19,64,Low,Medium,No,8,59,LOW,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,150
2,24,98,Medium,Medium,Yes,7,91,MEDIUM,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,150
3,29,89,Low,Medium,Yes,8,98,MEDIUM,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,150
4,19,92,Medium,Medium,Yes,6,65,MEDIUM,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,150
5,19,88,Medium,Medium,Yes,8,89,MEDIUM,Yes,3,Medium,Medium,Public,Positive,3,No,Postgraduate,Near,Male,150
6,29,84,Medium,Low,Yes,7,68,LOW,Yes,1,Low,Medium,Private,Neutral,2,No,High School,Moderate,Male,150
7,25,78,Low,High,Yes,6,50,MEDIUM,Yes,1,High,High,Public,Negative,2,No,High School,Far,Male,150
8,17,94,Medium,High,No,6,80,HIGH,Yes,0,Medium,Low,Private,Neutral,1,No,College,Near,Male,150
9,23,98,Medium,Medium,Yes,8,71,MEDIUM,Yes,0,High,High,Public,Positive,5,No,High School,Moderate,Male,150

# 2- Data preprocessing

## Check data for duplicated and remove them

In [4]:
df.duplicated().sum()

np.int64(1005)

In [5]:
df.drop_duplicates(inplace = True)

In [6]:
df.duplicated().sum()

np.int64(0)

## Check Data for missing values

In [7]:
df.isnull().sum()

Hours_Studied                 18
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

## Fixing Data type of hours_studied column

### We need to deal with these NaN values before converting them to integers
### so we will convert them from string to a float (because floats can store NaN)
### then compute the mean in missin values and conver

In [8]:
df['Hours_Studied'] = pd.to_numeric(df['Hours_Studied'], errors='coerce')

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 6642 entries, 0 to 7608
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6592 non-null   float64
 1   Attendance                  6642 non-null   int64
 2   Parental_Involvement        6642 non-null   str
 3   Access_to_Resources         6642 non-null   str
 4   Extracurricular_Activities  6642 non-null   str
 5   Sleep_Hours                 6642 non-null   int64
 6   Previous_Scores             6642 non-null   int64
 7   Motivation_Level            6642 non-null   str
 8   Internet_Access             6642 non-null   str
 9   Tutoring_Sessions           6642 non-null   int64
 10  Family_Income               6642 non-null   str
 11  Teacher_Quality             6564 non-null   str
 12  School_Type                 6642 non-null   str
 13  Peer_Influence              6642 non-null   str
 14  Physical_Activity           6642 non-null   int64
 15  Learning_Disabilities       6642 non-null   str
 16  Parental_Education_Level    6552 non-null   str
 17  Distance_from_Home          6575 non-null   str
 18  Gender                      6642 non-null   str
 19  Exam_Score                  6642 non-null   int64
dtypes: float64(1), int64(6), str(13)
memory usage: 1.1 MB

In [10]:
df['Hours_Studied'] = df['Hours_Studied'].fillna(df['Hours_Studied'].median())

In [11]:
df['Hours_Studied'] = df['Hours_Studied'].astype(int)

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 6642 entries, 0 to 7608
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6642 non-null   int64
 1   Attendance                  6642 non-null   int64
 2   Parental_Involvement        6642 non-null   str
 3   Access_to_Resources         6642 non-null   str
 4   Extracurricular_Activities  6642 non-null   str
 5   Sleep_Hours                 6642 non-null   int64
 6   Previous_Scores             6642 non-null   int64
 7   Motivation_Level            6642 non-null   str
 8   Internet_Access             6642 non-null   str
 9   Tutoring_Sessions           6642 non-null   int64
 10  Family_Income               6642 non-null   str
 11  Teacher_Quality             6564 non-null   str
 12  School_Type                 6642 non-null   str
 13  Peer_Influence              6642 non-null   str
 14  Physical_Activity           6642 non-null   int64
 15  Learning_Disabilities       6642 non-null   str
 16  Parental_Education_Level    6552 non-null   str
 17  Distance_from_Home          6575 non-null   str
 18  Gender                      6642 non-null   str
 19  Exam_Score                  6642 non-null   int64
dtypes: int64(7), str(13)
memory usage: 1.1 MB

## Handle extreme values

In [13]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6642.000000,6642.000000,6642.000000,6642.000000,6642.000000,6642.000000,6642.000000
mean,19.973201,79.967028,7.026649,75.063234,1.493978,2.968534,67.351099
std,5.972824,11.548330,1.467937,14.409365,1.230556,1.030949,8.302927
min,1.000000,60.000000,4.000000,50.000000,0.000000,0.000000,-20.000000
25%,16.000000,70.000000,6.000000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.000000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.000000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.000000,100.000000,8.000000,6.000000,150.000000

Exam_Score column has some extreme values

In [14]:
mean = int(df.loc[(df['Exam_Score'] >= 0) & (df['Exam_Score'] <= 100), 'Exam_Score'].mean())

df.loc[df['Exam_Score'] > 100, 'Exam_Score'] = mean
df.loc[df['Exam_Score'] < 0, 'Exam_Score'] = mean

In [15]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6642.000000,6642.000000,6642.000000,6642.000000,6642.000000,6642.000000,6642.000000
mean,19.973201,79.967028,7.026649,75.063234,1.493978,2.968534,67.233062
std,5.972824,11.548330,1.467937,14.409365,1.230556,1.030949,3.862437
min,1.000000,60.000000,4.000000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.000000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.000000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.000000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.000000,100.000000,8.000000,6.000000,100.000000

## Handle inconsistend formatting in motivation_level column

In [16]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,LOW,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,LOW,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,67
2,24,98,Medium,Medium,Yes,7,91,MEDIUM,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,67
3,29,89,Low,Medium,Yes,8,98,MEDIUM,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,67
4,19,92,Medium,Medium,Yes,6,65,MEDIUM,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,67

## check if there are other columns with incorrect formatting

In [17]:
for col in df.select_dtypes(include='str').columns:
    print(f'{col}: {df[col].unique()}')

Parental_Involvement: <StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str
Access_to_Resources: <StringArray>
['High', 'Medium', 'Low']
Length: 3, dtype: str
Extracurricular_Activities: <StringArray>
['No', 'Yes']
Length: 2, dtype: str
Motivation_Level: <StringArray>
[       'LOW',     'MEDIUM',       'HIGH',   '  High  ', '  Medium  ',
    '  Low  ',       'High',     'Medium',        'Low']
Length: 9, dtype: str
Internet_Access: <StringArray>
['Yes', 'No']
Length: 2, dtype: str
Family_Income: <StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str
Teacher_Quality: <StringArray>
['Medium', 'High', 'Low', nan]
Length: 4, dtype: str
School_Type: <StringArray>
['Public', 'Private']
Length: 2, dtype: str
Peer_Influence: <StringArray>
['Positive', 'Negative', 'Neutral']
Length: 3, dtype: str
Learning_Disabilities: <StringArray>
['No', 'Yes']
Length: 2, dtype: str
Parental_Education_Level: <StringArray>
['High School', 'College', 'Postgraduate', nan]
Length: 4, dtype: str
Distance_from_Home: <StringArray>
['Near', 'Moderate', 'Far', nan]
Length: 4, dtype: str
Gender: <StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [18]:
def fix_formatting(df, cols):
    for col in cols:
        df[col] = df[col].str.strip().str.title()
    return df

df = fix_formatting(df, ['Motivation_Level'])

In [19]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,67
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,67
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,67
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,67

In [20]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6642.000000,6642.000000,6642.000000,6642.000000,6642.000000,6642.000000,6642.000000
mean,19.973201,79.967028,7.026649,75.063234,1.493978,2.968534,67.233062
std,5.972824,11.548330,1.467937,14.409365,1.230556,1.030949,3.862437
min,1.000000,60.000000,4.000000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.000000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.000000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.000000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.000000,100.000000,8.000000,6.000000,100.000000

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 6642 entries, 0 to 7608
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6642 non-null   int64
 1   Attendance                  6642 non-null   int64
 2   Parental_Involvement        6642 non-null   str
 3   Access_to_Resources         6642 non-null   str
 4   Extracurricular_Activities  6642 non-null   str
 5   Sleep_Hours                 6642 non-null   int64
 6   Previous_Scores             6642 non-null   int64
 7   Motivation_Level            6642 non-null   str
 8   Internet_Access             6642 non-null   str
 9   Tutoring_Sessions           6642 non-null   int64
 10  Family_Income               6642 non-null   str
 11  Teacher_Quality             6564 non-null   str
 12  School_Type                 6642 non-null   str
 13  Peer_Influence              6642 non-null   str
 14  Physical_Activity           6642 non-null   int64
 15  Learning_Disabilities       6642 non-null   str
 16  Parental_Education_Level    6552 non-null   str
 17  Distance_from_Home          6575 non-null   str
 18  Gender                      6642 non-null   str
 19  Exam_Score                  6642 non-null   int64
dtypes: int64(7), str(13)
memory usage: 1.1 MB

In [22]:
for col in ['Teacher_Quality', 'Parental_Education_Level', 'Distance_from_Home']:
    df[col].fillna(df[col].mode()[0])

/tmp/ipykernel_67057/23606774.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].mode()[0], inplace=True)

In [23]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64